# Chọn một bộ GHC và thư viện ổn định. LTS 22.7 sử dụng GHC 9.6.5
resolver: lts-22.7


# Chỉ định các gói con (packages) trong dự án của bạn
# Stack sẽ tự động tìm các file .cabal hoặc package.yaml trong các thư mục này
packages:
  - ./server
  - ./client
  - ./shared

# Tùy chọn bổ sung (không bắt buộc nhưng hữu ích)
extra-deps:  # Nơi để thêm các thư viện không có trong resolver
- gloss-juicy-0.2.3@sha256:0c3bca95237cbf91f8b3b1936a0661f1e0457acd80502276d54d6c5210f88b25,1618
- derive-storable-plugin-0.2.3.7@sha256:f82b5cc67d7affbb41040d3a5812e6a587894e232e7a5d5ccb33103836e51fa6,2868
- gloss-raster-massiv-0.1.1.5@sha256:beb83234e5f39bacb62fd27f517e5af7acc9437a0d27c08b5787a0575efbbca3,4073


# Cấu hình chung cho toàn bộ dự án
allow-newer: true